### ISSUE TITLE
C:\Python27>python pywallet.py --dumpwallet --datadir=. > wallet.txt Traceback (most recent call last):   File "pywallet.py", line 2111, in parse_wallet     d.update(parse_BlockLocator(vds)) TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by suhel1986** [joric/pywallet#2]
I am getting this error in cmd

C:\Python27>python pywallet.py --dumpwallet --datadir=. > wallet.txt
Traceback (most recent call last):
  File "pywallet.py", line 2111, in parse_wallet
    d.update(parse_BlockLocator(vds))
TypeError: 'NoneType' object is not iterable

What needs to be changed below?line 2111

def getSBoxValue(self,num):
		"""Retrieves a given S-Box Value"""
		return self.sbox[num]

	def getSBoxInvert(self,num):
		"""Retrieves a given Inverted S-Box Value"""
		return self.rsbox[num]

	def rotate(self, word):
		""" Rijndael's key schedule rotate operation.

**Comment by BarrowHill** [comment]
I have the same question, maybe we need to specify --namecoin or --bitcoin address type?? Because TypeError: 'NoneType' object is not iterable
means that there is no type by default.

**Comment by ashraful1980** [comment]
Pywallet is very old and the wallet.dat file format has changed since Pywallet was last updated (2014).

It looks like the script does not handle some of the new data fields that are now included in the wallet.dat file. It should theoretically be possible to modify the script to either handle or ignore the unknown fields.

If you just want to dump the file and don't care about making a "valid" wallet.dat... you can edit the pywallet.py file:

Change Line #2111 from:
Code:
				d.update(parse_BlockLocator(vds))
to:
Code:
				#d.update(parse_BlockLocator(vds))


Then on Line #2502, change:
Code:
			json_db['bestblock'] = d['hashes'][0][::-1].encode('hex_codec')
to:
Code:
			print("ignored") #json_db['bestblock'] = d['hashes'][0][::-1].encode('hex_codec')
